"""add_currencies

Revision ID: 2b6efd8813ea
Revises: 7cc914b635a5
Create Date: 2025-11-25 05:42:19.821537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b6efd8813ea"
down_revision: Union[str, None] = "7cc914b635a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=5), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currencies_code"), "currencies", ["code"], unique=True)

    currencies_table = sa.table(
        "currencies",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("symbol", sa.String),
    )
    op.bulk_insert(
        currencies_table,
        [
            {"code": "RUB", "name": "Российский рубль", "symbol": "₽"},
            {"code": "USD", "name": "Доллар США", "symbol": "$"},
            {"code": "EUR", "name": "Евро", "symbol": "€"},
            {"code": "GBP", "name": "Фунт стерлингов", "symbol": "£"},
            {"code": "CNY", "name": "Китайский юань", "symbol": "¥"},
            {"code": "JPY", "name": "Японская иена", "symbol": "¥"},
            {"code": "BTC", "name": "Биткоин", "symbol": "₿"},
            {"code": "ETH", "name": "Эфириум", "symbol": "Ξ"},
            {"code": "USDT", "name": "Tether", "symbol": "₮"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currencies_code"), table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
