version: "3.9"

services:
  scheduler:
    image: ${IMAGE_PREFIX}/scheduler:${IMAGE_TAG}
    environment:
      DEBUG: "false"
      SQLALCHEMY_ECHO: "false"
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EXCHANGE_RATE_JOB_TIMEZONE: UTC
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  internal:
    external: true
    name: finances_internal
